project_id = "qohhrliaecdtaeyfhcvb"

[functions.ai-chat]
verify_jwt = false

[functions.subscription-expiry-notify]
verify_jwt = false

[functions.generate-exam]
verify_jwt = false

[functions.grade-essay]
verify_jwt = false

[functions.send-content-notification]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
