export const MIGRATION_SQL = `-- ============================================================================
-- MIGRATION: Add missing library book infrastructure to project B
-- Source of truth: project A (Lovable Cloud), extracted via pg_dump 2026-07-14
-- Generated by library-diag-b edge function operation
-- ============================================================================

-- Prerequisite helper functions (missing on B)
CREATE OR REPLACE FUNCTION public.touch_library_conv_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $$
BEGIN
  NEW.updated_at = now();
  NEW.last_message_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.library_jobs_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

-- ============================================================================
-- Below: verbatim pg_dump schema-only output for the 15 book-related tables
-- ============================================================================

--
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = on;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: library_processing_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_processing_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    stage text NOT NULL,
    state text DEFAULT 'queued'::text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    progress integer DEFAULT 0 NOT NULL,
    last_error text,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    kind text DEFAULT 'extract_book'::text NOT NULL,
    page_number integer,
    locked_by text,
    locked_at timestamp with time zone,
    max_attempts integer DEFAULT 3 NOT NULL,
    CONSTRAINT library_processing_jobs_kind_check_v2 CHECK ((kind = ANY (ARRAY['extract_book'::text, 'extract_page'::text, 'build_index'::text, 'embed_book'::text]))),
    CONSTRAINT library_processing_jobs_stage_check CHECK ((stage = ANY (ARRAY['upload'::text, 'split'::text, 'ocr'::text, 'sections'::text, 'embed'::text, 'explain'::text, 'tts'::text, 'finalize'::text]))),
    CONSTRAINT library_processing_jobs_state_check2 CHECK ((state = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])))
);


--
-- Name: library_access_tiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_access_tiers (
    code text NOT NULL,
    name_ar text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_book_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_book_chunks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    page_number integer NOT NULL,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    token_count integer,
    embedding public.vector(1536),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_book_conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_book_conversations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    student_id uuid NOT NULL,
    current_page integer,
    current_section_id uuid,
    last_index_id uuid,
    last_message_at timestamp with time zone DEFAULT now() NOT NULL,
    summary text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_book_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_book_index (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    parent_id uuid,
    kind text DEFAULT 'section'::text NOT NULL,
    title text NOT NULL,
    summary text,
    keywords text[] DEFAULT '{}'::text[] NOT NULL,
    page_start integer NOT NULL,
    page_end integer NOT NULL,
    order_index integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    embedding public.vector(1536),
    CONSTRAINT library_book_index_kind_check CHECK ((kind = ANY (ARRAY['chapter'::text, 'lesson'::text, 'section'::text, 'heading'::text, 'note'::text])))
);


--
-- Name: library_book_pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_book_pages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    page_number integer NOT NULL,
    image_path text,
    ocr_text text,
    width integer,
    height integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    page_summary text,
    keywords text[] DEFAULT '{}'::text[] NOT NULL,
    embedding public.vector(1536),
    ocr_confidence numeric
);


--
-- Name: library_book_sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_book_sections (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    page_id uuid NOT NULL,
    kind text NOT NULL,
    bbox jsonb NOT NULL,
    order_index integer DEFAULT 0 NOT NULL,
    raw_text text,
    embedding public.vector(1536),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT library_book_sections_kind_check CHECK ((kind = ANY (ARRAY['title'::text, 'paragraph'::text, 'image'::text, 'table'::text, 'equation'::text, 'list'::text])))
);


--
-- Name: library_books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_books (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text,
    cover_url text,
    pdf_path text,
    education_type text NOT NULL,
    stage_id uuid,
    track_id uuid,
    subject_id uuid,
    subject_name_ar text,
    page_count integer,
    file_size bigint,
    status text DEFAULT 'draft'::text NOT NULL,
    processing_progress integer DEFAULT 0 NOT NULL,
    processing_stage text,
    processing_error text,
    access_tier text DEFAULT 'free'::text NOT NULL,
    published_at timestamp with time zone,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    grade_id uuid,
    section_id uuid,
    CONSTRAINT library_books_education_type_check CHECK ((education_type = ANY (ARRAY['عام'::text, 'أزهر'::text, 'both'::text]))),
    CONSTRAINT library_books_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'uploading'::text, 'processing'::text, 'ready'::text, 'failed'::text, 'paused'::text, 'hidden'::text])))
);


--
-- Name: library_conversation_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_conversation_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    conversation_id uuid NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    scope text DEFAULT 'page'::text NOT NULL,
    page_number integer,
    section_id uuid,
    audio_path text,
    tokens_input integer,
    tokens_output integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT library_conversation_messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text]))),
    CONSTRAINT library_conversation_messages_scope_check CHECK ((scope = ANY (ARRAY['page'::text, 'book'::text, 'section'::text])))
);


--
-- Name: library_generated_quizzes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_generated_quizzes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    scope text NOT NULL,
    scope_ref jsonb DEFAULT '{}'::jsonb NOT NULL,
    prompt_hash text NOT NULL,
    questions jsonb NOT NULL,
    question_count integer DEFAULT 0 NOT NULL,
    created_by uuid,
    hit_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_recommendations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    source_book_id uuid,
    source_page integer,
    kind text NOT NULL,
    payload jsonb NOT NULL,
    score numeric DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_section_explanations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_section_explanations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    book_id uuid NOT NULL,
    page_id uuid,
    section_id uuid,
    variant text DEFAULT 'default'::text NOT NULL,
    prompt_hash text NOT NULL,
    text_ar text NOT NULL,
    audio_path text,
    voice text,
    tokens_input integer,
    tokens_output integer,
    hit_count integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT library_section_explanations_variant_check CHECK ((variant = ANY (ARRAY['default'::text, 'deeper'::text, 'simpler'::text])))
);


--
-- Name: library_student_book_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_student_book_progress (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    book_id uuid NOT NULL,
    last_page integer DEFAULT 1 NOT NULL,
    last_section_id uuid,
    reading_seconds integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_student_memory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_student_memory (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    last_book_id uuid,
    last_page integer,
    last_section_id uuid,
    last_conversation_id uuid,
    last_question text,
    last_answer text,
    last_audio_path text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_student_weaknesses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.library_student_weaknesses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    book_id uuid,
    topic text NOT NULL,
    page_number integer,
    section_id uuid,
    wrong_count integer DEFAULT 0 NOT NULL,
    right_count integer DEFAULT 0 NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    strength_score numeric DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: library_access_tiers library_access_tiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_access_tiers
    ADD CONSTRAINT library_access_tiers_pkey PRIMARY KEY (code);


--
-- Name: library_book_chunks library_book_chunks_book_id_page_number_chunk_index_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_chunks
    ADD CONSTRAINT library_book_chunks_book_id_page_number_chunk_index_key UNIQUE (book_id, page_number, chunk_index);


--
-- Name: library_book_chunks library_book_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_chunks
    ADD CONSTRAINT library_book_chunks_pkey PRIMARY KEY (id);


--
-- Name: library_book_conversations library_book_conversations_book_id_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_conversations
    ADD CONSTRAINT library_book_conversations_book_id_student_id_key UNIQUE (book_id, student_id);


--
-- Name: library_book_conversations library_book_conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_conversations
    ADD CONSTRAINT library_book_conversations_pkey PRIMARY KEY (id);


--
-- Name: library_book_index library_book_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_index
    ADD CONSTRAINT library_book_index_pkey PRIMARY KEY (id);


--
-- Name: library_book_pages library_book_pages_book_id_page_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_pages
    ADD CONSTRAINT library_book_pages_book_id_page_number_key UNIQUE (book_id, page_number);


--
-- Name: library_book_pages library_book_pages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_pages
    ADD CONSTRAINT library_book_pages_pkey PRIMARY KEY (id);


--
-- Name: library_book_sections library_book_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_sections
    ADD CONSTRAINT library_book_sections_pkey PRIMARY KEY (id);


--
-- Name: library_books library_books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_pkey PRIMARY KEY (id);


--
-- Name: library_conversation_messages library_conversation_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_conversation_messages
    ADD CONSTRAINT library_conversation_messages_pkey PRIMARY KEY (id);


--
-- Name: library_generated_quizzes library_generated_quizzes_book_id_prompt_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_generated_quizzes
    ADD CONSTRAINT library_generated_quizzes_book_id_prompt_hash_key UNIQUE (book_id, prompt_hash);


--
-- Name: library_generated_quizzes library_generated_quizzes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_generated_quizzes
    ADD CONSTRAINT library_generated_quizzes_pkey PRIMARY KEY (id);


--
-- Name: library_processing_jobs library_processing_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_processing_jobs
    ADD CONSTRAINT library_processing_jobs_pkey PRIMARY KEY (id);


--
-- Name: library_recommendations library_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_recommendations
    ADD CONSTRAINT library_recommendations_pkey PRIMARY KEY (id);


--
-- Name: library_section_explanations library_section_explanations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_section_explanations
    ADD CONSTRAINT library_section_explanations_pkey PRIMARY KEY (id);


--
-- Name: library_student_book_progress library_student_book_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_book_progress
    ADD CONSTRAINT library_student_book_progress_pkey PRIMARY KEY (id);


--
-- Name: library_student_book_progress library_student_book_progress_student_id_book_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_book_progress
    ADD CONSTRAINT library_student_book_progress_student_id_book_id_key UNIQUE (student_id, book_id);


--
-- Name: library_student_memory library_student_memory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_memory
    ADD CONSTRAINT library_student_memory_pkey PRIMARY KEY (id);


--
-- Name: library_student_memory library_student_memory_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_memory
    ADD CONSTRAINT library_student_memory_student_id_key UNIQUE (student_id);


--
-- Name: library_student_weaknesses library_student_weaknesses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_weaknesses
    ADD CONSTRAINT library_student_weaknesses_pkey PRIMARY KEY (id);


--
-- Name: library_student_weaknesses library_student_weaknesses_student_id_book_id_topic_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_weaknesses
    ADD CONSTRAINT library_student_weaknesses_student_id_book_id_topic_key UNIQUE (student_id, book_id, topic);


--
-- Name: idx_library_books_edu; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_books_edu ON public.library_books USING btree (education_type);


--
-- Name: idx_library_books_full_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_books_full_scope ON public.library_books USING btree (stage_id, grade_id, section_id, track_id, subject_id);


--
-- Name: idx_library_books_grade; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_books_grade ON public.library_books USING btree (grade_id);


--
-- Name: idx_library_books_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_books_scope ON public.library_books USING btree (stage_id, track_id, subject_id);


--
-- Name: idx_library_books_section; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_books_section ON public.library_books USING btree (section_id);


--
-- Name: idx_library_books_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_books_status ON public.library_books USING btree (status);


--
-- Name: idx_library_conv_msgs; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_conv_msgs ON public.library_conversation_messages USING btree (conversation_id, created_at);


--
-- Name: idx_library_conv_student; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_conv_student ON public.library_book_conversations USING btree (student_id, last_message_at DESC);


--
-- Name: idx_library_expl_book; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_expl_book ON public.library_section_explanations USING btree (book_id);


--
-- Name: idx_library_expl_prompt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_expl_prompt ON public.library_section_explanations USING btree (prompt_hash);


--
-- Name: idx_library_index_book; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_index_book ON public.library_book_index USING btree (book_id, order_index);


--
-- Name: idx_library_index_pages; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_index_pages ON public.library_book_index USING btree (book_id, page_start, page_end);


--
-- Name: idx_library_jobs_book; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_jobs_book ON public.library_processing_jobs USING btree (book_id);


--
-- Name: idx_library_jobs_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_jobs_state ON public.library_processing_jobs USING btree (state);


--
-- Name: idx_library_pages_book; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_pages_book ON public.library_book_pages USING btree (book_id, page_number);


--
-- Name: idx_library_pages_ocr_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_pages_ocr_trgm ON public.library_book_pages USING gin (ocr_text public.gin_trgm_ops);


--
-- Name: idx_library_sections_book; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_sections_book ON public.library_book_sections USING btree (book_id);


--
-- Name: idx_library_sections_page; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_sections_page ON public.library_book_sections USING btree (page_id, order_index);


--
-- Name: idx_library_sections_vec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_library_sections_vec ON public.library_book_sections USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: library_book_chunks_book_page_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_book_chunks_book_page_idx ON public.library_book_chunks USING btree (book_id, page_number);


--
-- Name: library_book_chunks_content_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_book_chunks_content_trgm ON public.library_book_chunks USING gin (content public.gin_trgm_ops);


--
-- Name: library_book_chunks_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_book_chunks_embedding_hnsw ON public.library_book_chunks USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: library_book_index_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_book_index_embedding_hnsw ON public.library_book_index USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: library_book_pages_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_book_pages_embedding_hnsw ON public.library_book_pages USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: library_book_sections_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_book_sections_embedding_hnsw ON public.library_book_sections USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: library_jobs_book_page_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_jobs_book_page_idx ON public.library_processing_jobs USING btree (book_id, page_number);


--
-- Name: library_jobs_kind_state_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_jobs_kind_state_idx ON public.library_processing_jobs USING btree (kind, state, created_at);


--
-- Name: library_jobs_state_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX library_jobs_state_idx ON public.library_processing_jobs USING btree (state, created_at);


--
-- Name: library_jobs_unique_book_prepare_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX library_jobs_unique_book_prepare_idx ON public.library_processing_jobs USING btree (book_id) WHERE ((kind = 'extract_book'::text) AND (state = ANY (ARRAY['queued'::text, 'running'::text])));


--
-- Name: library_jobs_unique_page_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX library_jobs_unique_page_idx ON public.library_processing_jobs USING btree (book_id, page_number) WHERE (kind = 'extract_page'::text);


--
-- Name: uq_library_expl_section_variant; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_library_expl_section_variant ON public.library_section_explanations USING btree (section_id, variant) WHERE (section_id IS NOT NULL);


--
-- Name: library_student_book_progress trg_bp_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_bp_updated BEFORE UPDATE ON public.library_student_book_progress FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_book_chunks trg_chunks_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_chunks_updated BEFORE UPDATE ON public.library_book_chunks FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_books trg_library_books_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_library_books_updated_at BEFORE UPDATE ON public.library_books FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_book_conversations trg_library_conv_touch; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_library_conv_touch BEFORE UPDATE ON public.library_book_conversations FOR EACH ROW EXECUTE FUNCTION public.touch_library_conv_updated_at();


--
-- Name: library_section_explanations trg_library_expl_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_library_expl_updated_at BEFORE UPDATE ON public.library_section_explanations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_processing_jobs trg_library_jobs_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_library_jobs_updated_at BEFORE UPDATE ON public.library_processing_jobs FOR EACH ROW EXECUTE FUNCTION public.library_jobs_touch_updated_at();


--
-- Name: library_book_pages trg_library_pages_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_library_pages_updated_at BEFORE UPDATE ON public.library_book_pages FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_book_sections trg_library_sections_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_library_sections_updated_at BEFORE UPDATE ON public.library_book_sections FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_student_memory trg_memory_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_memory_updated BEFORE UPDATE ON public.library_student_memory FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_student_weaknesses trg_weak_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_weak_updated BEFORE UPDATE ON public.library_student_weaknesses FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: library_book_chunks library_book_chunks_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_chunks
    ADD CONSTRAINT library_book_chunks_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_book_conversations library_book_conversations_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_conversations
    ADD CONSTRAINT library_book_conversations_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_book_conversations library_book_conversations_current_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_conversations
    ADD CONSTRAINT library_book_conversations_current_section_id_fkey FOREIGN KEY (current_section_id) REFERENCES public.library_book_sections(id) ON DELETE SET NULL;


--
-- Name: library_book_conversations library_book_conversations_last_index_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_conversations
    ADD CONSTRAINT library_book_conversations_last_index_id_fkey FOREIGN KEY (last_index_id) REFERENCES public.library_book_index(id) ON DELETE SET NULL;


--
-- Name: library_book_conversations library_book_conversations_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_conversations
    ADD CONSTRAINT library_book_conversations_student_id_fkey FOREIGN KEY (student_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: library_book_index library_book_index_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_index
    ADD CONSTRAINT library_book_index_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_book_index library_book_index_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_index
    ADD CONSTRAINT library_book_index_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.library_book_index(id) ON DELETE CASCADE;


--
-- Name: library_book_pages library_book_pages_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_pages
    ADD CONSTRAINT library_book_pages_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_book_sections library_book_sections_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_sections
    ADD CONSTRAINT library_book_sections_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_book_sections library_book_sections_page_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_book_sections
    ADD CONSTRAINT library_book_sections_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.library_book_pages(id) ON DELETE CASCADE;


--
-- Name: library_books library_books_access_tier_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_access_tier_fkey FOREIGN KEY (access_tier) REFERENCES public.library_access_tiers(code);


--
-- Name: library_books library_books_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;


--
-- Name: library_books library_books_grade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES public.library_grades(id) ON DELETE SET NULL;


--
-- Name: library_books library_books_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.library_sections(id) ON DELETE SET NULL;


--
-- Name: library_books library_books_stage_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES public.library_stages(id) ON DELETE SET NULL;


--
-- Name: library_books library_books_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.library_subjects(id) ON DELETE SET NULL;


--
-- Name: library_books library_books_track_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_books
    ADD CONSTRAINT library_books_track_id_fkey FOREIGN KEY (track_id) REFERENCES public.library_tracks(id) ON DELETE SET NULL;


--
-- Name: library_conversation_messages library_conversation_messages_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_conversation_messages
    ADD CONSTRAINT library_conversation_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.library_book_conversations(id) ON DELETE CASCADE;


--
-- Name: library_conversation_messages library_conversation_messages_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_conversation_messages
    ADD CONSTRAINT library_conversation_messages_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.library_book_sections(id) ON DELETE SET NULL;


--
-- Name: library_generated_quizzes library_generated_quizzes_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_generated_quizzes
    ADD CONSTRAINT library_generated_quizzes_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_processing_jobs library_processing_jobs_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_processing_jobs
    ADD CONSTRAINT library_processing_jobs_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_recommendations library_recommendations_source_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_recommendations
    ADD CONSTRAINT library_recommendations_source_book_id_fkey FOREIGN KEY (source_book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_section_explanations library_section_explanations_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_section_explanations
    ADD CONSTRAINT library_section_explanations_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_section_explanations library_section_explanations_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_section_explanations
    ADD CONSTRAINT library_section_explanations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;


--
-- Name: library_section_explanations library_section_explanations_page_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_section_explanations
    ADD CONSTRAINT library_section_explanations_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.library_book_pages(id) ON DELETE CASCADE;


--
-- Name: library_section_explanations library_section_explanations_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_section_explanations
    ADD CONSTRAINT library_section_explanations_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.library_book_sections(id) ON DELETE CASCADE;


--
-- Name: library_student_book_progress library_student_book_progress_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_book_progress
    ADD CONSTRAINT library_student_book_progress_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_student_book_progress library_student_book_progress_last_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_book_progress
    ADD CONSTRAINT library_student_book_progress_last_section_id_fkey FOREIGN KEY (last_section_id) REFERENCES public.library_book_sections(id) ON DELETE SET NULL;


--
-- Name: library_student_memory library_student_memory_last_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_memory
    ADD CONSTRAINT library_student_memory_last_book_id_fkey FOREIGN KEY (last_book_id) REFERENCES public.library_books(id) ON DELETE SET NULL;


--
-- Name: library_student_memory library_student_memory_last_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_memory
    ADD CONSTRAINT library_student_memory_last_conversation_id_fkey FOREIGN KEY (last_conversation_id) REFERENCES public.library_book_conversations(id) ON DELETE SET NULL;


--
-- Name: library_student_memory library_student_memory_last_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_memory
    ADD CONSTRAINT library_student_memory_last_section_id_fkey FOREIGN KEY (last_section_id) REFERENCES public.library_book_sections(id) ON DELETE SET NULL;


--
-- Name: library_student_weaknesses library_student_weaknesses_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_weaknesses
    ADD CONSTRAINT library_student_weaknesses_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id) ON DELETE CASCADE;


--
-- Name: library_student_weaknesses library_student_weaknesses_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.library_student_weaknesses
    ADD CONSTRAINT library_student_weaknesses_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.library_book_sections(id) ON DELETE SET NULL;


--
-- Name: library_access_tiers Admins manage access tiers; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage access tiers" ON public.library_access_tiers TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_books Admins manage all library books; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage all library books" ON public.library_books TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_section_explanations Admins manage explanations; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage explanations" ON public.library_section_explanations TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_processing_jobs Admins manage jobs; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage jobs" ON public.library_processing_jobs USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_book_pages Admins manage pages; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage pages" ON public.library_book_pages TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_book_sections Admins manage sections; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage sections" ON public.library_book_sections TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_access_tiers Anyone can read access tiers; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Anyone can read access tiers" ON public.library_access_tiers FOR SELECT USING (true);


--
-- Name: library_book_pages Readable when book is readable; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Readable when book is readable" ON public.library_book_pages FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.library_books b
  WHERE ((b.id = library_book_pages.book_id) AND (b.status = 'ready'::text) AND (b.access_tier = 'free'::text)))));


--
-- Name: library_book_sections Readable when book is readable; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Readable when book is readable" ON public.library_book_sections FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.library_books b
  WHERE ((b.id = library_book_sections.book_id) AND (b.status = 'ready'::text) AND (b.access_tier = 'free'::text)))));


--
-- Name: library_section_explanations Readable when book is readable; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Readable when book is readable" ON public.library_section_explanations FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.library_books b
  WHERE ((b.id = library_section_explanations.book_id) AND (b.status = 'ready'::text) AND (b.access_tier = 'free'::text)))));


--
-- Name: library_books Students view scoped ready free library books; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Students view scoped ready free library books" ON public.library_books FOR SELECT TO authenticated USING (((status = 'ready'::text) AND (access_tier = 'free'::text) AND (public.has_role(auth.uid(), 'admin'::public.app_role) OR (EXISTS ( SELECT 1
   FROM ((((public.profiles p
     LEFT JOIN public.library_stages st ON ((st.id = library_books.stage_id)))
     LEFT JOIN public.library_grades gr ON ((gr.id = library_books.grade_id)))
     LEFT JOIN public.library_sections sec ON ((sec.id = library_books.section_id)))
     LEFT JOIN public.library_tracks tr ON ((tr.id = library_books.track_id)))
  WHERE ((p.id = auth.uid()) AND (COALESCE(p.role, 'student'::text) = 'student'::text) AND ((library_books.education_type = 'both'::text) OR (p.education_type IS NULL) OR (library_books.education_type = p.education_type)) AND ((library_books.stage_id IS NULL) OR (st.code = p.stage)) AND ((library_books.grade_id IS NULL) OR (gr.code =
        CASE
            WHEN ((p.stage = 'preparatory'::text) AND (p.grade = 'first'::text)) THEN 'pr1'::text
            WHEN ((p.stage = 'preparatory'::text) AND (p.grade = 'second'::text)) THEN 'pr2'::text
            WHEN ((p.stage = 'preparatory'::text) AND (p.grade = 'third'::text)) THEN 'pr3'::text
            WHEN ((p.stage = 'secondary'::text) AND (p.grade = 'first'::text)) THEN 'sec1'::text
            WHEN ((p.stage = 'secondary'::text) AND (p.grade = 'second'::text)) THEN 'sec2'::text
            WHEN ((p.stage = 'secondary'::text) AND (p.grade = 'third'::text)) THEN 'sec3'::text
            WHEN ((p.stage = 'primary'::text) AND (p.grade = 'first'::text)) THEN 'p1'::text
            WHEN ((p.stage = 'primary'::text) AND (p.grade = 'second'::text)) THEN 'p2'::text
            WHEN ((p.stage = 'primary'::text) AND (p.grade = 'third'::text)) THEN 'p3'::text
            WHEN ((p.stage = 'primary'::text) AND (p.grade = 'fourth'::text)) THEN 'p4'::text
            WHEN ((p.stage = 'primary'::text) AND (p.grade = 'fifth'::text)) THEN 'p5'::text
            WHEN ((p.stage = 'primary'::text) AND (p.grade = 'sixth'::text)) THEN 'p6'::text
            ELSE p.grade
        END)) AND ((library_books.section_id IS NULL) OR (sec.code = 'shared'::text) OR (sec.code =
        CASE
            WHEN (p.education_type = 'عام'::text) THEN 'general'::text
            WHEN (p.education_type = 'أزهر'::text) THEN 'azhar'::text
            ELSE sec.code
        END)) AND ((library_books.track_id IS NULL) OR (tr.code = 'none'::text) OR (
        CASE
            WHEN (p.section = ANY (ARRAY['علمي علوم'::text, 'علمى علوم'::text])) THEN 'sci_science'::text
            WHEN (p.section = ANY (ARRAY['علمي رياضة'::text, 'علمى رياضة'::text])) THEN 'sci_math'::text
            WHEN (p.section = ANY (ARRAY['أدبي'::text, 'ادبي'::text, 'أدبى'::text, 'ادبى'::text])) THEN 'literary'::text
            ELSE 'none'::text
        END = tr.code))))))));


--
-- Name: library_book_index admins manage library index; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admins manage library index" ON public.library_book_index TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_book_conversations admins read all book conversations; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admins read all book conversations" ON public.library_book_conversations FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_conversation_messages admins read all library conversation messages; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admins read all library conversation messages" ON public.library_conversation_messages FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_book_chunks chunks readable by entitled users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "chunks readable by entitled users" ON public.library_book_chunks FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.library_books b
  WHERE ((b.id = library_book_chunks.book_id) AND ((b.access_tier = 'free'::text) OR (b.created_by = auth.uid()) OR public.has_role(auth.uid(), 'admin'::public.app_role))))));


--
-- Name: library_access_tiers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_access_tiers ENABLE ROW LEVEL SECURITY;

--
-- Name: library_book_chunks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_book_chunks ENABLE ROW LEVEL SECURITY;

--
-- Name: library_book_conversations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_book_conversations ENABLE ROW LEVEL SECURITY;

--
-- Name: library_book_index; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_book_index ENABLE ROW LEVEL SECURITY;

--
-- Name: library_book_pages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_book_pages ENABLE ROW LEVEL SECURITY;

--
-- Name: library_book_sections; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_book_sections ENABLE ROW LEVEL SECURITY;

--
-- Name: library_books; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_books ENABLE ROW LEVEL SECURITY;

--
-- Name: library_conversation_messages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_conversation_messages ENABLE ROW LEVEL SECURITY;

--
-- Name: library_generated_quizzes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_generated_quizzes ENABLE ROW LEVEL SECURITY;

--
-- Name: library_processing_jobs library_jobs_admin_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY library_jobs_admin_read ON public.library_processing_jobs FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: library_processing_jobs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_processing_jobs ENABLE ROW LEVEL SECURITY;

--
-- Name: library_recommendations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_recommendations ENABLE ROW LEVEL SECURITY;

--
-- Name: library_section_explanations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_section_explanations ENABLE ROW LEVEL SECURITY;

--
-- Name: library_student_book_progress; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_student_book_progress ENABLE ROW LEVEL SECURITY;

--
-- Name: library_student_memory; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_student_memory ENABLE ROW LEVEL SECURITY;

--
-- Name: library_student_weaknesses; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.library_student_weaknesses ENABLE ROW LEVEL SECURITY;

--
-- Name: library_generated_quizzes quizzes readable by entitled users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "quizzes readable by entitled users" ON public.library_generated_quizzes FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.library_books b
  WHERE ((b.id = library_generated_quizzes.book_id) AND ((b.access_tier = 'free'::text) OR (b.created_by = auth.uid()) OR public.has_role(auth.uid(), 'admin'::public.app_role))))));


--
-- Name: library_student_book_progress student manages own book progress; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "student manages own book progress" ON public.library_student_book_progress TO authenticated USING ((auth.uid() = student_id)) WITH CHECK ((auth.uid() = student_id));


--
-- Name: library_student_memory student manages own memory; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "student manages own memory" ON public.library_student_memory TO authenticated USING ((auth.uid() = student_id)) WITH CHECK ((auth.uid() = student_id));


--
-- Name: library_student_weaknesses student manages own weaknesses; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "student manages own weaknesses" ON public.library_student_weaknesses TO authenticated USING ((auth.uid() = student_id)) WITH CHECK ((auth.uid() = student_id));


--
-- Name: library_recommendations student sees own recommendations; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "student sees own recommendations" ON public.library_recommendations TO authenticated USING ((auth.uid() = student_id)) WITH CHECK ((auth.uid() = student_id));


--
-- Name: library_conversation_messages students access messages of own conversations; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "students access messages of own conversations" ON public.library_conversation_messages TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.library_book_conversations c
  WHERE ((c.id = library_conversation_messages.conversation_id) AND (c.student_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.library_book_conversations c
  WHERE ((c.id = library_conversation_messages.conversation_id) AND (c.student_id = auth.uid())))));


--
-- Name: library_book_conversations students manage own book conversation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "students manage own book conversation" ON public.library_book_conversations TO authenticated USING ((auth.uid() = student_id)) WITH CHECK ((auth.uid() = student_id));


--
-- Name: library_book_index students read index of accessible books; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "students read index of accessible books" ON public.library_book_index FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.library_books b
  WHERE ((b.id = library_book_index.book_id) AND (b.status = 'ready'::text) AND (b.access_tier = 'free'::text)))));


--
-- Name: TABLE library_processing_jobs; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_processing_jobs TO authenticated;
GRANT ALL ON TABLE public.library_processing_jobs TO service_role;


--
-- Name: TABLE library_access_tiers; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,MAINTAIN ON TABLE public.library_access_tiers TO anon;
GRANT ALL ON TABLE public.library_access_tiers TO authenticated;
GRANT ALL ON TABLE public.library_access_tiers TO service_role;


--
-- Name: TABLE library_book_chunks; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_book_chunks TO authenticated;
GRANT ALL ON TABLE public.library_book_chunks TO service_role;


--
-- Name: TABLE library_book_conversations; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_book_conversations TO authenticated;
GRANT ALL ON TABLE public.library_book_conversations TO service_role;


--
-- Name: TABLE library_book_index; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_book_index TO authenticated;
GRANT ALL ON TABLE public.library_book_index TO service_role;


--
-- Name: TABLE library_book_pages; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_book_pages TO authenticated;
GRANT ALL ON TABLE public.library_book_pages TO service_role;


--
-- Name: TABLE library_book_sections; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_book_sections TO authenticated;
GRANT ALL ON TABLE public.library_book_sections TO service_role;


--
-- Name: TABLE library_books; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_books TO authenticated;
GRANT ALL ON TABLE public.library_books TO service_role;
GRANT SELECT ON TABLE public.library_books TO anon;


--
-- Name: TABLE library_conversation_messages; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_conversation_messages TO authenticated;
GRANT ALL ON TABLE public.library_conversation_messages TO service_role;


--
-- Name: TABLE library_generated_quizzes; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_generated_quizzes TO authenticated;
GRANT ALL ON TABLE public.library_generated_quizzes TO service_role;


--
-- Name: TABLE library_recommendations; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_recommendations TO authenticated;
GRANT ALL ON TABLE public.library_recommendations TO service_role;


--
-- Name: TABLE library_section_explanations; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_section_explanations TO authenticated;
GRANT ALL ON TABLE public.library_section_explanations TO service_role;


--
-- Name: TABLE library_student_book_progress; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_student_book_progress TO authenticated;
GRANT ALL ON TABLE public.library_student_book_progress TO service_role;


--
-- Name: TABLE library_student_memory; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_student_memory TO authenticated;
GRANT ALL ON TABLE public.library_student_memory TO service_role;


--
-- Name: TABLE library_student_weaknesses; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.library_student_weaknesses TO authenticated;
GRANT ALL ON TABLE public.library_student_weaknesses TO service_role;


--
--


`;
