// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.109.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Mudrik Plus profile: full name, email, role, education stage, section, and education type.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "id, full_name, email, phone, role, stage, section, education_type, grade, student_code, teacher_code, avatar_url"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-wallet.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.109.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_wallet_default = defineTool2({
  name: "get_my_wallet",
  title: "Get my wallet balance",
  description: "Return the signed-in user's Mudrik Plus wallet balance in EGP.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("wallets").select("balance, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const balance = data?.balance ?? 0;
    return {
      content: [{ type: "text", text: `Wallet balance: ${balance} EGP` }],
      structuredContent: { balance, updated_at: data?.updated_at ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.109.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_notifications_default = defineTool3({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "Return the most recent notifications visible to the signed-in Mudrik Plus user.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum notifications to return (default 10)."),
    unread_only: z.boolean().optional().describe("If true, return only unread notifications.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser3(ctx);
    let query = client.from("notifications").select("*").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (unread_only) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-exams.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.109.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_exams_default = defineTool4({
  name: "list_my_exams",
  title: "List my exams",
  description: "Return exams the signed-in user can currently see in Mudrik Plus. Row-Level Security enforces visibility per student/teacher.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum exams to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("exams").select("id, title, subject, stage, section, education_type, status, created_at, duration_minutes, total_questions").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { exams: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qohhrliaecdtaeyfhcvb";
var mcp_default = defineMcp({
  name: "modrek-plus-mcp",
  title: "Mudrik Plus",
  version: "0.1.0",
  instructions: "Read-only tools for the signed-in Mudrik Plus user. Use get_my_profile to read the user's account, get_my_wallet for their wallet balance, list_my_notifications for recent notifications, and list_my_exams for exams they can currently access. Every tool runs as the authenticated user under Row-Level Security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_wallet_default, list_my_notifications_default, list_my_exams_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
