import { PenTool } from "lucide-react";
import { DiagramBlock, SvgBlock } from "./DiagramBlock";

export interface LessonDiagramData {
  format: "mermaid" | "svg";
  code: string;
  title?: string;
}

/**
 * Standalone illustration card shown under a full lesson explanation.
 * The diagram is generated by the assistant separately from the answer text,
 * so it always renders as its own visual block instead of inline markdown.
 */
export function LessonDiagramCard({ diagram }: { diagram: LessonDiagramData }) {
  if (!diagram?.code) return null;
  return (
    <section className="mt-4 overflow-hidden rounded-2xl border-2 border-primary/25 bg-primary/[0.03]" aria-label={diagram.title || "رسم توضيحي للدرس"}>
      <div className="flex items-center gap-2 border-b border-primary/20 bg-primary/10 px-3 py-2 text-[13px] font-bold text-primary">
        <PenTool className="h-4 w-4 shrink-0" />
        <h3 className="truncate text-[13px] font-bold">{diagram.title || "رسم توضيحي للدرس"}</h3>
      </div>
      <div className="px-2 pb-2">
        {diagram.format === "svg" ? <SvgBlock code={diagram.code} /> : <DiagramBlock code={diagram.code} />}
      </div>
    </section>
  );
}

export default LessonDiagramCard;
