// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

type Database = any;

// Official production project (modrekplus.com). The Android build workflow
// injects these env vars at build time and verifies the bundle. Web (Vercel)
// also injects them. No fallback is provided on purpose — building without
// the env vars must fail loudly rather than silently shipping the wrong DB.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY at build time. " +
    "Both must be set to the official production project (qteuqfntsocsdbjmdvmr)."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
