android {
    signingConfigs {
        release {
            storeFile file('keystore/release.keystore')
            storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD') ?: 'changeit'
            keyAlias System.getenv('ANDROID_KEY_ALIAS') ?: 'release'
            keyPassword System.getenv('ANDROID_KEY_PASSWORD') ?: 'changeit'
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
